services:
  app:
    build: .
    container_name: apsit-notifier
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./:/app  # drop :ro if you want live edits
      - app_venv:/app/.venv
    command: ["uv", "run", "--no-sync", "main.py"]

volumes:
  app_venv:
